
development:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_development
  pool: 5
  username: michaelreinhart
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_test
  pool: 5
  username: michaelreinhart
  password:
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_production
  username: michaelreinhart
  password:
  host: localhost
